### ISSUE TITLE
Username slot 6b not holding values

### ISSUE THREAD

**Issue by jaroszke** [onlykey/OnlyKey-Firmware#22]
Steps to reproduce:
US version

1. Set all Pins
2. Set label on slot 6b
3. Set username
4. Submit
5. Use slot 6b in text editor
notice no output displayed in text editor 

[slot6bnotholdingvalues-serial.txt](https://github.com/onlykey/OnlyKey-Firmware/files/370349/slot6bnotholdingvalues-serial.txt)

**Comment by onlykey** [comment]
fixed
