### ISSUE TITLE
How to know if the firmware has been tampered with

### ISSUE THREAD

**Issue by Coder2012** [onlykey/OnlyKey-Firmware#29]
In your installation instructions you have ambiguities:

_To load the US version you will use the OnlyKey_Alpha_US.cpp.hex firmware included in the zip file (OnlyKey-Firmware-master/OnlyKey_Beta_US/OnlyKey_Beta_US.cpp.hex)._

There is no Alpha version but as expected there is a Beta version.

You then ask users to ensure they check the SHA256 hash of the firmware against two entries that are listed as:

OnlyKey_Alpha_US.cpp.hex - f1390f31fe426efc8979d5b8c59391957582de94d81ff5abfaab89bdc3710103
OnlyKey_Alpha_IN.cpp.hex - 54746d8c26a3e87e16139aed2889905f3f4b7269d866e2fefd79c2bb02ee12e5

I can only assume this has not been updated as they are obviously Alpha versions not Beta versions, and indeed the hash entries do not appear to match.

**Comment by onlykey** [comment]
Removed reference to this from README and moved to quick start guide here www.crp.to/ok new release hashes published there https://github.com/onlykey/OnlyKey-Firmware/releases/tag/v0.2-beta.2
