### ISSUE TITLE
Firmware Too Large

### ISSUE THREAD

**Issue by SteffeyDev** [onlykey/OnlyKey-Firmware#30]
With the new firmware, Teensy (OS X) is saying the file is too large.  I downloaded on both Safari and Chrome, got same SHA 256 sum (5b311d84354152d22c114c9b405a23be4bc95cf7d5ea9445ba5ae5b9265d0e2d).  Sum does not match guide but most likely because creators did not update guide with new sums after uploading new firmware.  See attached picture.  Note: I renamed the firmware file so that you could see the "(too large)" part.

Anyone else having this problem?

![teensy](https://cloud.githubusercontent.com/assets/10255587/17740300/120d30e4-6466-11e6-8ea4-f7e5a5701a80.png)

**Comment by onlykey** [comment]
Yes that is the correct SHA256 sum the quick start guide was updated earlier today. No one else has reported this issue. A user did have a similar issue here but found they were not making good contact with the touch points - https://groups.google.com/forum/#!topic/onlykey/Ed8ylswIQmc

**Comment by onlykey** [comment]
The correct file size is 211KB

**Comment by onlykey** [comment]
Just double checked teensy loader on Mac and it works fine here 
![image](https://cloud.githubusercontent.com/assets/18121756/17744297/154c0758-6475-11e6-9d2f-780b9f7c62eb.png)

**Comment by SteffeyDev** [comment]
I didn't realize you had to make the connection before loading the file, that fixed it for me, thanks!

**Comment by onlykey** [comment]
Glad this was resolved. Let me know if there is somewhere I might be able to add a note in the quick start guide to make this easier.
